version: "3"
networks:
  myevents:
  monitoring:

volumes:
  prometheus-data:
  grafana-data:

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - "5672:5672"
  

  events-db:
    image: mongo


  bookings-db:
    image: mongo




